### ISSUE TITLE
Support WASM?

### ISSUE THREAD

**Issue by Youdiie** [paulkre/bevy_image_export#3]
Hello again :)
I could save 1 frame using this wonderful crate, and wanted to use in web.
However, I got this error `panicked at 'condvar wait not supported'`, and found there is no multi-thread in WASM. 
In your code, I guessed, `app.sub_app_mut(RenderApp)` ran on multi-thread.

So is there any plan to support WASM?
Or did I make any mistake again?

**Comment by paulkre** [comment]
Hi, you're correct that the current version of this plugin does not support WASM in the browser. This limitation is primarily due to the plugin's need for access to the file system. While it is probably theoretically possible to add support by having the browser download exported frames, this approach wouldn't be ideal for exporting a long sequence of frames. However, for your specific use case, it could be a viable solution.

If you want, you could post a PR with an implementation for WASM. I would be happy to review it.
